# Generated by Django 4.2.2 on 2023-07-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('query', models.TextField()),
            ],
        ),
    ]
